//! Printing a baked graph as Rust source (LEAF-SPEC §6.4.2).
//!
//! **This module derives nothing.** It renders the [`Baked`] value `crate::bake` built, field
//! for field, and every decision it could have made was made by a ★ crate before it got here
//! (§6.4.1). If a `match` in this file ever grows a branch that computes rather than spells,
//! that is the second implementation §2's MUST-NOT list is about.
//!
//! What it emits, and nothing else:
//!
//! - one `static` per distinct artifact, through [`eio_leaf::include_module!`] — never a bare
//!   `include_bytes!`, which is align-1 and gives §6.2's target no unaligned-access guarantee;
//! - one `pub static GRAPH: BakedGraph` of data.
//!
//! **No `fn` and no control flow**, which is the rule that keeps a second lifecycle driver,
//! a second router and a second property-resolution rule from being born one convenience at a
//! time. The only call expressions in the output are `const fn`s evaluated in a `static`
//! initializer — `eio_leaf::leaf_limits()`, `PropertySource::new`/`unset`, `Limits::new` —
//! which are how the runtime crate's own values reach the file without this crate retyping
//! them.
//!
//! # String literals
//!
//! Every string is rendered with `{:?}`, which is `str`'s `Debug` and produces a valid Rust
//! string literal: it escapes `"`, `\` and control characters and leaves everything else
//! alone. Property sources go through it too, and they are the reason it matters — an
//! expression is `"\"kitchen.cold\""` as often as not (SERVICE §4).
//!
//! # Enum variants
//!
//! `Overflow`, `Capability` and `PropertyType` are rendered with `{:?}` as well, which for a
//! unit variant is its Rust identifier. That is deliberately not a hand-written mapping
//! table: a mapping is a thing that drifts when a variant is added, and these three enums
//! belong to `eio-host-core` and `eio-manifest` rather than to this crate.

use std::fmt::Write as _;

use eio_leaf::graph::{BakedGraph, BakedInstance};

use crate::Baked;

/// The generated file, as text.
///
/// It is a **build artifact and MUST NOT be checked in** (§6.4.2): it is derived from the
/// service file, the manifests and the artifacts, and a checked-in copy would be a second
/// source of truth for a graph whose whole point is that the service file is the source. It
/// is written into the build directory and `include!`d, which is why every module path in it
/// is absolute.
pub fn emit(baked: &Baked) -> String {
    let mut out = String::new();
    let graph = baked.graph;

    out.push_str(
        "// GENERATED by `eio-leaf-gen` — LEAF-SPEC §6.4's baked graph. DO NOT EDIT, and do\n\
         // not check this file in (§6.4.2): the service file is the source, and a checked-in\n\
         // copy would be a second one. It is `include!`d by a hand-written, per-target\n\
         // `main`, which hands `GRAPH` to `eio_leaf::spawn_graph` (§2, §6.4).\n\
         //\n\
         // It contains one `static` of data and nothing else: no `fn`, no control flow.\n\n",
    );

    for (index, artifact) in baked.artifacts.iter().enumerate() {
        let _ = writeln!(
            out,
            "/// {} — linked into the image (§6.3), over-aligned (§6.4.2).",
            artifact.path.display()
        );
        let _ = writeln!(
            out,
            "static MODULE_{index}: &[u8] = eio_leaf::include_module!({:?});\n",
            artifact.path.display().to_string()
        );
    }

    let _ = writeln!(
        out,
        "/// This node's whole configuration (LEAF §6.4.2).\n\
         pub static GRAPH: eio_leaf::graph::BakedGraph = eio_leaf::graph::BakedGraph {{"
    );
    node(&mut out, graph);
    instances(&mut out, baked);
    connections(&mut out, graph);
    let _ = writeln!(
        out,
        "    overflow: eio_leaf::graph::Overflow::{:?},",
        graph.overflow
    );
    transport(&mut out, graph);
    out.push_str("};\n");
    out
}

/// `node.toml`'s baked half (§6.4.3).
fn node(out: &mut String, graph: &BakedGraph) {
    let _ = writeln!(out, "    node: eio_leaf::graph::BakedNode {{");
    let _ = writeln!(out, "        id: {:?},", graph.node.id);
    let _ = match graph.node.name {
        Some(name) => writeln!(out, "        name: Some({name:?}),"),
        None => writeln!(out, "        name: None,"),
    };
    let _ = writeln!(out, "        service: {:?},", graph.node.service);
    // The runtime crate's own §4.2 values, called rather than retyped: a generator that wrote
    // `Limits::new(4096, 8)` would be a second statement of numbers §4 fixes, and §6.4.3 says
    // limits are baked while budgets are not even a build input.
    let _ = writeln!(out, "        limits: eio_leaf::leaf_limits(),");
    let _ = writeln!(out, "    }},");
}

/// The instances, in the graph's own order — which *is* the `Endpoint::instance` numbering.
fn instances(out: &mut String, baked: &Baked) {
    let _ = writeln!(out, "    instances: &[");
    for (instance, artifact) in baked.graph.instances.iter().zip(&baked.instance_artifact) {
        let _ = writeln!(out, "        eio_leaf::graph::BakedInstance {{");
        let _ = writeln!(out, "            id: {:?},", instance.id);
        let _ = writeln!(out, "            block: {:?},", instance.block);
        let _ = writeln!(out, "            module: MODULE_{artifact},");
        let _ = writeln!(out, "            inputs: {},", strs(instance.inputs));
        let _ = writeln!(out, "            outputs: {},", strs(instance.outputs));
        props(out, instance);
        let _ = writeln!(
            out,
            "            capabilities: &[{}],",
            instance
                .capabilities
                .iter()
                .map(|capability| format!("eio_leaf::graph::Capability::{capability:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        let _ = writeln!(out, "        }},");
    }
    let _ = writeln!(out, "    ],");
}

/// What `eio_host_core::resolve` returned, in `prop_id` order (ABI §11.1, §5.2).
///
/// `new` and `unset` are `PropertySource`'s own `const` constructors, which is what makes a
/// resolved property list expressible as a `static` at all (§6.4.2). `unset` is a legal
/// declaration and not an omission: it keeps its `prop_id` slot and answers `ERR_NOT_FOUND`.
fn props(out: &mut String, instance: &BakedInstance) {
    let _ = writeln!(out, "            props: &[");
    for property in instance.props {
        let ty = format!("eio_leaf::graph::PropertyType::{:?}", property.ty);
        let _ = match property.source {
            Some(source) => writeln!(
                out,
                "                eio_leaf::graph::PropertySource::new({:?}, {ty}, {source:?}),",
                property.name
            ),
            None => writeln!(
                out,
                "                eio_leaf::graph::PropertySource::unset({:?}, {ty}),",
                property.name
            ),
        };
    }
    let _ = writeln!(out, "            ],");
}

/// The wiring, as names — resolved on the device by `Routes::resolve` (§6.4.1).
fn connections(out: &mut String, graph: &BakedGraph) {
    let _ = writeln!(out, "    connections: &[");
    for connection in graph.connections {
        let _ = writeln!(
            out,
            "        eio_leaf::graph::BakedConnection {{ from: ({:?}, {:?}), to: ({:?}, {:?}) }},",
            connection.from.0, connection.from.1, connection.to.0, connection.to.1
        );
    }
    let _ = writeln!(out, "    ],");
}

/// `pubsub.toml`'s baked half (DAEMON §7.1), or `None` for a node that runs no bridge.
fn transport(out: &mut String, graph: &BakedGraph) {
    let Some(transport) = &graph.transport else {
        let _ = writeln!(out, "    transport: None,");
        return;
    };
    let _ = writeln!(
        out,
        "    transport: Some(eio_leaf::graph::BakedTransport {{"
    );
    let _ = writeln!(out, "        bus: {:?},", transport.bus);
    let _ = writeln!(out, "        candidates: {},", strs(transport.candidates));
    let _ = match transport.pinned {
        Some(pinned) => writeln!(out, "        pinned: Some({pinned:?}),"),
        None => writeln!(out, "        pinned: None,"),
    };
    let _ = match transport.key {
        Some(key) => writeln!(
            out,
            "        key: Some(&[{}]),",
            key.iter()
                .map(|byte| format!("0x{byte:02x}"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        None => writeln!(out, "        key: None,"),
    };
    let _ = writeln!(out, "    }}),");
}

/// A `&'static [&'static str]` literal, order preserved — for a port list that is the port
/// numbering, order is the content.
fn strs(items: &[&str]) -> String {
    format!(
        "&[{}]",
        items
            .iter()
            .map(|item| format!("{item:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}
