// eieio-m9s.42: how the parity suites get at the daemon's and the Designer backend's own
// response shapes — read here, generated by `just shapes`, never by a test.
//
// # What this replaces, and why
//
// `schema-parity.test.ts` and `mock-parity.test.ts` used to shell out to `cargo test -p eio-cli
// --test response_shapes` from their own `beforeAll`, so that a bare `npm test` would be
// self-sufficient and could never compare against a file that was missing or stale. Both goals
// were right; the mechanism was not. A cold checkout has no cargo target directory, so that hook
// waits out a whole workspace build — past its own 120s timeout when `just ci`'s `test` stage is
// holding the target-directory lock at the same time. The suite then went green on the second
// run, against the now-warm cargo. Self-healing on a second run is the worst shape a CI failure
// can have: it teaches people to re-run instead of to look, and it makes a real wire-shape drift
// and a lock contention the same red.
//
// The artifact is a *prerequisite of the test run*, not something a hook races for. That is
// already this repo's pattern for exactly this class of problem: `crates/expr-wasm/pkg` is
// gitignored and generated, so every recipe that touches the SPA depends on `just designer-wasm`
// first. `just test-designer` now depends on `just shapes` the same way, and this module reads
// what that recipe wrote.
//
// # Neither goal is given up
//
// *Missing* and *stale* both still fail, loudly, and neither can be mistaken for a pass:
//
//   - Missing → [`readGeneratedShapes`] throws, naming the recipe to run. A parity check that
//     no-ops when it cannot find its input reports green while checking nothing, which is worse
//     than no check at all.
//   - Stale → the same, from a make-style mtime comparison against the Rust sources the artifact
//     is derived from ([`SOURCES`]). Under `just`, `shapes` has just rewritten the file, so this
//     never fires; it exists for the developer who ran `npm test` directly after editing the
//     daemon. Comparing against a schema snapshot from before that edit is precisely the drift
//     these suites exist to catch, so it is a failure, not a warning.
//
// What is given up is cargo running from inside vitest at all — the one thing that made the
// first run on a cold checkout different from every run after it.
import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

/** `designer/`, whichever directory vitest was started from. */
const DESIGNER_ROOT = process.cwd();
const REPO_ROOT = path.resolve(DESIGNER_ROOT, '..');

/** The two artifacts, and the paths each is derived from.
 *
 * `daemon` is written by `crates/cli/tests/response_shapes.rs` (the daemon's live `utoipa`
 * schemas, reached through `eio-cli`'s existing dependency on them); `designer` by
 * `crates/designer/tests/response_shapes.rs`. They are separate files on purpose and not an
 * accident of history — see the latter's module doc for why one shared file would make two
 * independent `cargo test` invocations two racing writers.
 *
 * `sources` is what staleness is measured against: the emitting test itself, plus the crate
 * whose schemas it reads. `crates/daemon/src` is the whole of what can change `NodeInfo`,
 * `TapRequest`, `ApiError`, `ServiceSummary`, `Tap` or the SSE payloads; `crates/designer/src`
 * the same for `SystemOut`/`NodeOut`. Coarser than a real dependency graph, deliberately: the
 * cost of an over-broad answer is one `just shapes` run, and the cost of an under-broad one is
 * the silent stale comparison this whole module exists to prevent. */
const SOURCES = {
  daemon: {
    artifact: 'designer/src/lib/api/__generated__/daemon-response-shapes.json',
    emitter: 'crates/cli/tests/response_shapes.rs',
    sources: ['crates/cli/tests/response_shapes.rs', 'crates/daemon/src'],
  },
  designer: {
    artifact: 'designer/src/lib/api/__generated__/designer-response-shapes.json',
    emitter: 'crates/designer/tests/response_shapes.rs',
    sources: ['crates/designer/tests/response_shapes.rs', 'crates/designer/src'],
  },
} as const;

export type ShapesSide = keyof typeof SOURCES;

/** What a developer who ran `npm test` directly needs to be told: the artifact is generated, by
 * this recipe, and the recipe is what to run — not "re-run the tests". */
function howToFix(side: ShapesSide, why: string): string {
  const { artifact, emitter } = SOURCES[side];
  return `${artifact} ${why}.

It is generated (and gitignored): \`${emitter}\` writes it from the live OpenAPI schemas, and
\`just shapes\` is what runs that. This suite deliberately does not generate it itself — see
\`designer/src/lib/api/generated-shapes.ts\` for why.

Run \`just test-designer\`, which regenerates it first. If you are running \`npm test\` directly
in \`designer/\`, run \`just shapes\` once beforehand.`;
}

/** The most recently modified file at or under `entry`, as an epoch-millisecond mtime.
 * Directories are walked; a missing path is 0, so a source tree that has been moved out from
 * under this cannot fabricate a staleness failure. */
function newestMtime(entry: string): number {
  let stat;
  try {
    stat = statSync(entry);
  } catch {
    return 0;
  }
  if (!stat.isDirectory()) return stat.mtimeMs;
  let newest = stat.mtimeMs;
  for (const child of readdirSync(entry, { withFileTypes: true })) {
    newest = Math.max(newest, newestMtime(path.join(entry, child.name)));
  }
  return newest;
}

/** Reads one side's generated shapes, or throws saying exactly what to run.
 *
 * Callers get the parsed JSON object as-is; picking `sse`, `required`, `types` and friends out
 * of it stays with the suite that reads them, since the two suites read different subsets. */
export function readGeneratedShapes(side: ShapesSide): Record<string, unknown> {
  const { artifact, sources } = SOURCES[side];
  const artifactPath = path.join(REPO_ROOT, artifact);

  let generatedAt: number;
  try {
    generatedAt = statSync(artifactPath).mtimeMs;
  } catch {
    throw new Error(howToFix(side, 'does not exist'));
  }

  for (const source of sources) {
    const changedAt = newestMtime(path.join(REPO_ROOT, source));
    if (changedAt > generatedAt) {
      throw new Error(howToFix(side, `is older than \`${source}\`, so it is stale`));
    }
  }

  return JSON.parse(readFileSync(artifactPath, 'utf-8')) as Record<string, unknown>;
}
