//! `cargo eio new` — the template block repo (SDK-SPEC §5.1).

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};
use clap::Args;

use crate::template::{self, FILES, Names};

/// The version of `eio-sdk` a generated block depends on.
///
/// `cargo-eio`'s own, because the two are released together (SCOPE §7.2) and a tool that
/// scaffolded a block against an SDK it had never been tested with would be guessing.
const SDK_VERSION: &str = env!("CARGO_PKG_VERSION");

/// `cargo eio new`'s arguments (SDK-SPEC §5.1).
#[derive(Debug, Args)]
pub struct NewArgs {
    /// The block's name — its registry name, its cargo package name, and the directory.
    ///
    /// ABI §11.1's `^[a-z0-9]([a-z0-9._-]*[a-z0-9])?$`, ≤64 bytes, and additionally without
    /// `.` because it is also a cargo package name.
    pub name: String,

    /// Where to create the block's directory. Defaults to the current directory.
    #[arg(long, value_name = "DIR")]
    pub path: Option<PathBuf>,

    /// Depend on a local eieio checkout's `crates/block-sdk` instead of the registry.
    ///
    /// `eio-test-host` is taken from its sibling. This is what the tooling's own tests use,
    /// so "the template builds out of the box" is measured rather than asserted (SDK §5.1).
    #[arg(long, value_name = "DIR")]
    pub sdk_path: Option<PathBuf>,
}

/// Writes the template block repo (SDK-SPEC §5.1) at `args.path`/`args.name`.
pub fn run(args: &NewArgs) -> anyhow::Result<()> {
    let name = check_name(&args.name)?;
    let names = Names::new(name);

    let root = args
        .path
        .clone()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(name);
    if root.exists() {
        bail!("{} already exists", root.display());
    }

    let (sdk, test_host) = match &args.sdk_path {
        Some(path) => local_dependencies(path)?,
        None => (
            format!("eio-sdk = \"{SDK_VERSION}\""),
            format!("eio-test-host = \"{SDK_VERSION}\""),
        ),
    };

    for file in &FILES {
        let path = root.join(file.path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }
        let rendered = template::render(file.source, &names, &sdk, &test_host);
        fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))?;
    }

    println!("Created block {name} in {}", root.display());
    println!("    cd {name} && cargo eio test");
    Ok(())
}

/// ABI §11.1's block-name rule, plus the one cargo adds.
///
/// The dot is §11.1-legal — the block name is a registry reference component (SCOPE §3.6) —
/// and cargo does not accept it in a package name. Refusing here beats generating a repo
/// whose first `cargo build` fails on a manifest the author did not write.
fn check_name(name: &str) -> anyhow::Result<&str> {
    if !eio_manifest::is_ref_name(name) {
        bail!(
            "{name:?} is not a valid block name: ABI §11.1 requires {} and at most {} bytes",
            eio_manifest::REF_NAME_PATTERN,
            eio_manifest::MAX_NAME_BYTES
        );
    }
    if name.contains('.') {
        bail!(
            "{name:?} cannot be a cargo package name: a block generated by `new` is a cargo package, and cargo does not accept `.`"
        );
    }
    Ok(name)
}

/// The two path dependency lines for a local eieio checkout.
fn local_dependencies(sdk_path: &Path) -> anyhow::Result<(String, String)> {
    let sdk = sdk_path
        .canonicalize()
        .with_context(|| format!("--sdk-path {}", sdk_path.display()))?;
    let test_host = sdk
        .parent()
        .map(|crates| crates.join("test-host"))
        .filter(|path| path.is_dir())
        .with_context(|| {
            format!(
                "{} has no `test-host` sibling; --sdk-path wants a checkout's `crates/block-sdk`",
                sdk.display()
            )
        })?;
    Ok((
        template::path_dependency("eio-sdk", &sdk),
        template::path_dependency("eio-test-host", &test_host),
    ))
}
