(module
  ;; Conforming, but not self-describing: no eio:manifest section (4.4 is a SHOULD).
  (memory (export "memory") 1)
  (func (export "eio_abi_version") (result i32)
    i32.const 65536)
  (func (export "eio_alloc") (param i32) (result i32)
    i32.const 0)
  (func (export "eio_free") (param i32 i32))
  (func (export "eio_configure") (param i32 i32) (result i32)
    i32.const 0)
  (func (export "eio_start") (result i32)
    i32.const 0)
  (func (export "eio_stop") (result i32)
    i32.const 0)
  (func (export "eio_process_signals") (param i32 i32 i32) (result i32)
    i32.const 0)
)
