(module
  ;; Conforming: core + timer + gpio imports, both paired callbacks, embedded manifest.
  (import "eio:core" "emit" (func (param i32 i32 i32) (result i32)))
  (import "eio:timer" "timer_set" (func (param i64 i32) (result i32)))
  (import "eio:gpio" "gpio_read" (func (param i32) (result i32)))
  (memory (export "memory") 1)
  (func (export "eio_abi_version") (result i32)
    i32.const 65536)
  (func (export "eio_alloc") (param i32) (result i32)
    i32.const 0)
  (func (export "eio_free") (param i32 i32))
  (func (export "eio_configure") (param i32 i32) (result i32)
    i32.const 0)
  (func (export "eio_start") (result i32)
    i32.const 0)
  (func (export "eio_stop") (result i32)
    i32.const 0)
  (func (export "eio_process_signals") (param i32 i32 i32) (result i32)
    i32.const 0)
  (func (export "eio_on_timer") (param i32) (result i32)
    i32.const 0)
  (func (export "eio_on_gpio") (param i32 i32) (result i32)
    i32.const 0)
  (@custom "eio:manifest" "{\"name\":\"probe\",\"version\":\"1.0.0\",\"abi\":{\"major\":1,\"minor\":0},\"capabilities\":[\"timer\", \"gpio\"],\"inputs\":[{\"name\":\"in\"}]}")
)
