//! Semantic validation: the ABI-SPEC §11.1 rules the deserializer cannot express.
//!
//! The split is deliberate. Presence, unknown fields, duplicate keys, JSON types
//! and the closed sets are structural, so `serde` enforces them while decoding and
//! reports a line and column. What is left over — patterns, semver, uniqueness
//! within a list, the portable target, and whether a `default` is a real expression
//! — needs the whole document in hand, and lives here.
//!
//! Validation is all-or-nothing and stops at the first violation. A manifest is not
//! a form to be corrected field by field: it is generated by the SDK from a block's
//! source (SDK §1), so the interesting case is "which rule did the generator break",
//! not "how many".

use alloc::collections::BTreeSet;
use alloc::string::ToString;

use crate::error::{Error, NameSite};
use crate::name::{is_port_name, is_ref_name, is_version};
use crate::schema::{Manifest, PORTABLE_TARGET};

impl Manifest {
    /// Checks every ABI §11.1 rule that survives deserialization.
    ///
    /// [`parse`](crate::parse) calls this, so a parsed manifest is always a valid
    /// one. It is public for the other direction: tooling that *builds* a manifest
    /// in memory (the `#[block]` macro, `cargo eio`) has to be able to check it
    /// without serializing first.
    pub fn validate(&self) -> Result<(), Error> {
        if !is_ref_name(&self.name) {
            return Err(Error::InvalidName {
                site: NameSite::Block,
                name: self.name.clone(),
            });
        }
        if !is_version(&self.version) {
            return Err(Error::InvalidVersion {
                version: self.version.clone(),
            });
        }

        // Capabilities cannot be misspelled — they are an enum — but they can be
        // repeated, and a repeat means the generator or the author is confused about
        // what the list is.
        unique(
            NameSite::Capability,
            self.capabilities.iter().map(|c| c.as_str()),
        )?;

        for (site, ports) in [
            (NameSite::Input, &self.inputs),
            (NameSite::Output, &self.outputs),
        ] {
            for port in ports {
                if !is_port_name(&port.name) {
                    return Err(Error::InvalidName {
                        site,
                        name: port.name.clone(),
                    });
                }
            }
            unique(site, ports.iter().map(|port| port.name.as_str()))?;
        }

        for property in &self.properties {
            if !is_port_name(&property.name) {
                return Err(Error::InvalidName {
                    site: NameSite::Property,
                    name: property.name.clone(),
                });
            }
            if let Some(default) = &property.default {
                validate_expression(&property.name, default)?;
            }
        }
        unique(
            NameSite::Property,
            self.properties.iter().map(|p| p.name.as_str()),
        )?;

        for (site, targets) in [
            (NameSite::Target, &self.targets),
            (NameSite::Aot, &self.aot),
        ] {
            for target in targets {
                if !is_ref_name(target) {
                    return Err(Error::InvalidName {
                        site,
                        name: target.clone(),
                    });
                }
            }
            unique(site, targets.iter().map(|target| target.as_str()))?;
        }

        if !self.targets.iter().any(|target| target == PORTABLE_TARGET) {
            return Err(Error::MissingPortableTarget);
        }

        Ok(())
    }
}

/// Rejects the first name that has already been seen in this namespace.
///
/// `BTreeSet` rather than sorting in place: the lists are short, and the borrow is
/// read-only so a caller's ordering — which *is* the port numbering — is untouched.
fn unique<'a>(site: NameSite, names: impl Iterator<Item = &'a str>) -> Result<(), Error> {
    let mut seen = BTreeSet::new();
    for name in names {
        if !seen.insert(name) {
            return Err(Error::DuplicateName {
                site,
                name: name.to_string(),
            });
        }
    }
    Ok(())
}

/// Parses and analyses a property default (ABI §11.1, EXPR §10).
///
/// The real parser and the real static analyser, not an approximation of them: a
/// manifest that ships `(frobnicate 1)` as a default is broken at build time, and
/// the only thing that knows `frobnicate` is not a builtin is the `expr` crate. No
/// evaluation happens — a default may be signal-dependent, and there is no signal
/// here.
fn validate_expression(property: &str, source: &str) -> Result<(), Error> {
    let invalid = |error| Error::InvalidDefault {
        property: property.to_string(),
        source: error,
    };
    let expr = eio_expr::parse(source).map_err(invalid)?;
    match eio_expr::analyze(&expr).first_error() {
        Some(error) => Err(invalid(*error)),
        None => Ok(()),
    }
}
