//! Semantic validation: the ABI-SPEC §11.1 rules the deserializer cannot express.
//!
//! The split is deliberate. Presence, unknown fields, duplicate keys, JSON types
//! and the closed sets are structural, so `serde` enforces them while decoding and
//! reports a line and column. What is left over — patterns, semver, uniqueness
//! within a list, the portable target, and whether a `default` is a real expression
//! — needs the whole document in hand, and lives here.
//!
//! Validation is all-or-nothing and stops at the first violation. A manifest is not
//! a form to be corrected field by field: it is generated by the SDK from a block's
//! source (SDK §1), so the interesting case is "which rule did the generator break",
//! not "how many".
//!
//! One rule here reaches past the document: a signal-independent property `default` is
//! *evaluated*, and its value checked against the property's declared type (ABI §11.1).
//! That is the only place this crate runs the interpreter, and
//! [`validate_expression`]'s documentation says what it deliberately does not reject.

use alloc::collections::BTreeSet;
use alloc::string::ToString;

use eio_signal::Value;

use crate::error::{Error, NameSite};
use crate::name::{is_port_name, is_ref_name, is_version};
use crate::schema::{Manifest, PORTABLE_TARGET, PropertyType};

impl Manifest {
    /// Checks every ABI §11.1 rule that survives deserialization.
    ///
    /// [`parse`](crate::parse) calls this, so a parsed manifest is always a valid
    /// one. It is public for the other direction: tooling that *builds* a manifest
    /// in memory (the `#[block]` macro, `cargo eio`) has to be able to check it
    /// without serializing first.
    pub fn validate(&self) -> Result<(), Error> {
        if !is_ref_name(&self.name) {
            return Err(Error::InvalidName {
                site: NameSite::Block,
                name: self.name.clone(),
            });
        }
        if !is_version(&self.version) {
            return Err(Error::InvalidVersion {
                version: self.version.clone(),
            });
        }

        // Capabilities cannot be misspelled — they are an enum — but they can be
        // repeated, and a repeat means the generator or the author is confused about
        // what the list is.
        unique(
            NameSite::Capability,
            self.capabilities.iter().map(|c| c.as_str()),
        )?;

        for (site, ports) in [
            (NameSite::Input, &self.inputs),
            (NameSite::Output, &self.outputs),
        ] {
            for port in ports {
                if !is_port_name(&port.name) {
                    return Err(Error::InvalidName {
                        site,
                        name: port.name.clone(),
                    });
                }
            }
            unique(site, ports.iter().map(|port| port.name.as_str()))?;
        }

        for property in &self.properties {
            if !is_port_name(&property.name) {
                return Err(Error::InvalidName {
                    site: NameSite::Property,
                    name: property.name.clone(),
                });
            }
            if let Some(default) = &property.default {
                validate_expression(&property.name, property.ty, default)?;
            }
        }
        unique(
            NameSite::Property,
            self.properties.iter().map(|p| p.name.as_str()),
        )?;

        for (site, targets) in [
            (NameSite::Target, &self.targets),
            (NameSite::Aot, &self.aot),
        ] {
            for target in targets {
                if !is_ref_name(target) {
                    return Err(Error::InvalidName {
                        site,
                        name: target.clone(),
                    });
                }
            }
            unique(site, targets.iter().map(|target| target.as_str()))?;
        }

        if !self.targets.iter().any(|target| target == PORTABLE_TARGET) {
            return Err(Error::MissingPortableTarget);
        }

        Ok(())
    }
}

/// Rejects the first name that has already been seen in this namespace.
///
/// `BTreeSet` rather than sorting in place: the lists are short, and the borrow is
/// read-only so a caller's ordering — which *is* the port numbering — is untouched.
fn unique<'a>(site: NameSite, names: impl Iterator<Item = &'a str>) -> Result<(), Error> {
    let mut seen = BTreeSet::new();
    for name in names {
        if !seen.insert(name) {
            return Err(Error::DuplicateName {
                site,
                name: name.to_string(),
            });
        }
    }
    Ok(())
}

/// Parses, analyses and — where it can — evaluates a property default
/// (ABI §11.1, EXPR §10).
///
/// The real parser, the real static analyser and the real interpreter, not
/// approximations of them: a manifest that ships `(frobnicate 1)` as a default is
/// broken at build time, and the only thing that knows `frobnicate` is not a builtin
/// is the `expr` crate.
///
/// A **signal-independent** default is evaluated here and its value checked against
/// the declared type, because `"type": "int"` with `"default": "true"` can never
/// produce an int and there is no reason to wait until configure time to say so.
/// Three things are deliberately *not* rejected:
///
/// - A **signal-dependent** default, which is not evaluated at all — there is no
///   signal to evaluate it against, and it is checked per signal at run time.
/// - A default that **fails to evaluate**. An evaluation failure is a per-signal
///   outcome (ABI §7.1) and budgets are host configuration (EXPR §9), so rejecting one
///   would make a document's validity depend on which host read it. `(/ 1 0)` is a
///   valid declaration that fails at configure time.
/// - Anything about a property with no default at all.
fn validate_expression(property: &str, declared: PropertyType, source: &str) -> Result<(), Error> {
    let invalid = |error| Error::InvalidDefault {
        property: property.to_string(),
        source: error,
    };
    let expr = eio_expr::parse(source).map_err(invalid)?;
    if let Some(error) = eio_expr::analyze(&expr).first_error() {
        return Err(invalid(*error));
    }

    if expr.is_signal_dependent() {
        return Ok(());
    }
    // `None` is ABI §7.1's `SIGNAL_NONE`, which is what a signal-independent
    // expression is defined against; the classifier above is what guarantees no sigil
    // can reach it and turn this into `NO_SIGNAL`.
    let Ok(folded) = eio_expr::eval(&expr, None) else {
        return Ok(());
    };
    if declared.accepts(&folded) {
        return Ok(());
    }
    Err(Error::DefaultTypeMismatch {
        property: property.to_string(),
        declared,
        folded: value_kind(&folded),
    })
}

/// What to call the type of a folded value in an error message.
///
/// Covers the whole ABI §6.3 space, not just the six property types: a default can fold
/// to an array, a map or null, none of which any `type` but `any` admits, and "folded to
/// a map" is the sentence that explains the rejection.
fn value_kind(value: &Value) -> &'static str {
    match value {
        Value::Null => "null",
        Value::Bool(_) => "bool",
        Value::Int(_) => "int",
        Value::Float(_) => "float",
        Value::Str(_) => "string",
        Value::Bytes(_) => "bytes",
        Value::Array(_) => "array",
        Value::Map(_) => "map",
    }
}
